### ISSUE TITLE
Should standard versions also be tested against the Version codelist?

### ISSUE THREAD

**Issue by dalepotter** [IATI/pyIATI#125]
Following the [code review comment](https://github.com/IATI/iati.core/pull/116#discussion_r136382894) @hayfield there is a question if [tests](https://github.com/IATI/iati.core/blob/master/iati/core/tests/test_constants.py#L5) for `iati.core.constants.STANDARD_VERSIONS` should also check that they are part of the Version codelist.

However, this may reduce the extensibility of the library will break things for developing the standard for future version upgrades.

**Comment by hayfield** [comment]
This relates to the question of what the `Version` codelist should contain, and whether it should be embedded, with a single value at each version.

**Comment by hayfield** [comment]
The answer to the question in the title (at least at present, in the context of #218 and #223) is: `no`
