### ISSUE TITLE
Add load_as_dataset function for Datasets

### ISSUE THREAD

**Issue by allthatilk** [IATI/pyIATI#228]
Would be good to have a helper function to load files external to pyIATI as Datasets.

**Comment by hayfield** [comment]
`iati.resources.load_as_dataset()` does something similar (need to ensure things work in a DRY manner so feature parity is maintained).

Need to see check what the scope of this (and the `resources` module as a whole) is with regards to loading files outside of library resources.

**Comment by hayfield** [comment]
In `0.3.0`.
