### ISSUE TITLE
Custom IATI Schemas cannot be created using external paths

### ISSUE THREAD

**Issue by allthatilk** [IATI/pyIATI#234]
Cannot create custom IATI Schemas as the current implementation depends on `pkg_resources` which does not access external paths.

**Comment by hayfield** [comment]
This should only impact Schemas - the Codelists, Datasets and Rulesets are created from strings so the loading-from-file can occur using standard Python calls.

**Comment by hayfield** [comment]
This relates to #177

**Comment by dalepotter** [comment]
Note: The instantiation of a Schema must be done using a path, since links to included schemas can be passed by string parameter, but the referred-to schemas cannot be found.

**Comment by hayfield** [comment]
In `0.3.0`.
